apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: challenge-api
  description: An example of a Backstage application.
  labels:
    language: nodejs
    label: test
  tags:
    - javascript
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
  annotations:
    backstage.io/source-location: url:https://github.com/tc-backstage-test/challenge-api
    github.com/project-slug: tc-backstage-test/challenge-api
    circleci.com/project-slug: github/tc-backstage-test/challenge-api
spec:
  type: website
  owner: backstage-dev
  lifecycle: experimental
  providesApis:
    - challenge-api
  consumesApis:
    - test1-api
  dependsOn:
    - component:test1
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: challenge-api
spec:
  type: openapi
  lifecycle: experimental
  owner: user:eisbilir
  definition:
    $text: https://github.com/tc-backstage-test/challenge-api/blob/dev/docs/swagger.yaml
